INSERT INTO series VALUES (1, NULL, NULL, NULL);
INSERT INTO series VALUES (2, NULL, NULL, NULL);

INSERT INTO books VALUES (1, NULL, NULL, NULL);
INSERT INTO books VALUES (2, NULL, NULL, NULL);
INSERT INTO books VALUES (3, NULL, NULL, NULL);
INSERT INTO books VALUES (4, NULL, NULL, NULL);
INSERT INTO books VALUES (5, NULL, NULL, NULL);
INSERT INTO books VALUES (6, NULL, NULL, NULL);

INSERT INTO characters VALUES (1, NULL, NULL, NULL, NULL);
INSERT INTO characters VALUES (2, NULL, NULL, NULL, NULL);
INSERT INTO characters VALUES (3, NULL, NULL, NULL, NULL);
INSERT INTO characters VALUES (4, NULL, NULL, NULL, NULL);
INSERT INTO characters VALUES (5, NULL, NULL, NULL, NULL);
INSERT INTO characters VALUES (6, NULL, NULL, NULL, NULL);
INSERT INTO characters VALUES (7, NULL, NULL, NULL, NULL);
INSERT INTO characters VALUES (8, NULL, NULL, NULL, NULL);

INSERT INTO subgenres VALUES (1, NULL);
INSERT INTO subgenres VALUES (2, NULL);

INSERT INTO authors VALUES (1, NULL);
INSERT INTO authors VALUES (2, NULL);

INSERT INTO character_books VALUES (1, NULL, NULL);
INSERT INTO character_books VALUES (2, NULL, NULL);
INSERT INTO character_books VALUES (3, NULL, NULL);
INSERT INTO character_books VALUES (4, NULL, NULL);
INSERT INTO character_books VALUES (5, NULL, NULL);
INSERT INTO character_books VALUES (6, NULL, NULL);
INSERT INTO character_books VALUES (7, NULL, NULL);
INSERT INTO character_books VALUES (8, NULL, NULL);
INSERT INTO character_books VALUES (9, NULL, NULL);
INSERT INTO character_books VALUES (10, NULL, NULL);
INSERT INTO character_books VALUES (11, NULL, NULL);
INSERT INTO character_books VALUES (12, NULL, NULL);
INSERT INTO character_books VALUES (13, NULL, NULL);
INSERT INTO character_books VALUES (14, NULL, NULL);
INSERT INTO character_books VALUES (15, NULL, NULL);
INSERT INTO character_books VALUES (16, NULL, NULL);
